version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wizmall621
    depends_on:
      - db
    volumes:
      - /var/www/html/wizmall:/var/www/html/ #로컬 볼륨을 마운트 (로컬에 /var/www/html/wizmall 폴더가 생성되어야 함)
    ports:
      - 8080:80
  db:
    container_name: mysql-wizmall
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pa55w0rd
      MYSQL_DATABASE: apmdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: apmsetup
    ports:
      - 6033:3306
